services:
  web:
    build: .
    ports:
      - "80:80"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - waxpsy-network

networks:
  waxpsy-network:
    driver: bridge